# Generated by Django 5.1.3 on 2024-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='events_img/')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=25)),
            ],
        ),
    ]
