# Generated by Django 5.1.3 on 2024-11-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default=123, upload_to='course_img/'),
            preserve_default=False,
        ),
    ]
