# Generated by Django 5.1.3 on 2024-11-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_teacher_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
