# Generated by Django 5.1.3 on 2024-11-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=123, upload_to='blog_img/'),
            preserve_default=False,
        ),
    ]
