# Generated by Django 5.1.3 on 2024-11-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_comment/'),
            preserve_default=False,
        ),
    ]
